### ISSUE TITLE
429 Too Many Requests when downloading images

### ISSUE THREAD

**Issue by zholmes1** [Olament/DeepMushroom#2]
When I run `datacollection/main.go`, the script runs but eventually starts to get 429 responses when downloading images. It just puts the XML response into the .jpg file and continues on. Is there a remedy for this?

**Comment by Olament** [comment]
Sounds like you hit a rate limit on iNaturalist. Try lower ```numberOfWorker ``` or add ```time.Sleep(1 * time.Second) ``` to the end of ```worker```
